-- MySQL Script generated by MySQL Workbench
-- Tue Sep 25 22:20:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `BD_EZIC`.`Expediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Expediente` (
  `idExpediente` INT NOT NULL AUTO_INCREMENT,
  `Folio` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExpediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_EZIC`.`Asesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Asesor` (
  `idAsesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  `Emp_Inst` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAsesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_EZIC`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Estudiante` (
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Carrera` VARCHAR(45) NOT NULL,
  `Expediente_idExpediente` INT NOT NULL,
  `Asesor_idAsesor` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`),
  INDEX `fk_Estudiante_Expediente1_idx` (`Expediente_idExpediente` ASC),
  INDEX `fk_Estudiante_Asesor1_idx` (`Asesor_idAsesor` ASC),
  CONSTRAINT `fk_Estudiante_Expediente1`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `BD_EZIC`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_Asesor1`
    FOREIGN KEY (`Asesor_idAsesor`)
    REFERENCES `BD_EZIC`.`Asesor` (`idAsesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_EZIC`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_EZIC`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Documento` (
  `idDocumento` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Contenido` BLOB NOT NULL,
  `Expediente_idExpediente` INT NOT NULL,
  `Estudiante_idEstudiante` INT NOT NULL,
  PRIMARY KEY (`idDocumento`),
  INDEX `fk_Documento_Expediente1_idx` (`Expediente_idExpediente` ASC),
  INDEX `fk_Documento_Estudiante1_idx` (`Estudiante_idEstudiante` ASC),
  CONSTRAINT `fk_Documento_Expediente1`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `BD_EZIC`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `BD_EZIC`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_EZIC`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Evaluacion` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `Criterios` VARCHAR(45) NOT NULL,
  `Puntaje` DECIMAL(3) NOT NULL,
  `Expediente_idExpediente` INT NOT NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `fk_Evaluacion_Expediente1_idx` (`Expediente_idExpediente` ASC),
  CONSTRAINT `fk_Evaluacion_Expediente1`
    FOREIGN KEY (`Expediente_idExpediente`)
    REFERENCES `BD_EZIC`.`Expediente` (`idExpediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_EZIC`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_EZIC`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `Alias` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;

