/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IF_Administrador;

import Clases.*;
import Conexiones.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarcia
 */
public class IF_AsignacionAsesores extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_AsignacionAsesores
     */
    Estudiante mEstudiante;
    ConexionEduardo mCE = new ConexionEduardo();
    DefaultTableModel TablaAsigEst = new DefaultTableModel();
    int ID_AlumnoParaAsesor = 0, ID_AsesorAsignado = 0;
    public IF_AsignacionAsesores() {
        initComponents();
        
        TablaAsigEst.addColumn("ID");
        TablaAsigEst.addColumn("Nombre");
        TablaAsigEst.addColumn("Carrera");
        BuscarTodosAlumnos();
        LlenarComboCarrera();
        LlenarComboAsesor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        TBAlumnosSinAsig = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        CBCarreraAsig = new javax.swing.JComboBox<>();
        BTN_BuscarEstAsig = new javax.swing.JButton();
        BTN_BuscarTodosEstAsig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LBL_AlumnoAsig = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBAsesoresAsignar = new javax.swing.JComboBox<>();
        BTN_Asignar = new javax.swing.JButton();

        setBorder(null);

        TBAlumnosSinAsig.setModel(TablaAsigEst);
        TBAlumnosSinAsig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBAlumnosSinAsigTBPuntajes1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TBAlumnosSinAsig);

        jLabel18.setText("Carrera:");

        CBCarreraAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCarreraAsigActionPerformed(evt);
            }
        });

        BTN_BuscarEstAsig.setText("Buscar");
        BTN_BuscarEstAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BuscarEstAsigActionPerformed(evt);
            }
        });

        BTN_BuscarTodosEstAsig.setText("Ver Todos");
        BTN_BuscarTodosEstAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BuscarTodosEstAsigActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        jLabel1.setText("Se le asignará al alumno(a):");

        LBL_AlumnoAsig.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        LBL_AlumnoAsig.setText("*******************");

        jLabel2.setFont(new java.awt.Font("Symbol", 0, 14)); // NOI18N
        jLabel2.setText("el asesor:");

        BTN_Asignar.setText("Asignar");
        BTN_Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBCarreraAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_BuscarEstAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_BuscarTodosEstAsig)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_Asignar))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBAsesoresAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LBL_AlumnoAsig))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_BuscarEstAsig)
                    .addComponent(BTN_BuscarTodosEstAsig)
                    .addComponent(jLabel18)
                    .addComponent(CBCarreraAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBL_AlumnoAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBAsesoresAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(BTN_Asignar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBAlumnosSinAsigTBPuntajes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBAlumnosSinAsigTBPuntajes1MouseClicked
        // TODO add your handling code here:
        int Seleccion = TBAlumnosSinAsig.rowAtPoint(evt.getPoint());
        ID_AlumnoParaAsesor = Integer.parseInt(TBAlumnosSinAsig.getModel().getValueAt(Seleccion, 0).toString());
        LBL_AlumnoAsig.setText(TBAlumnosSinAsig.getModel().getValueAt(Seleccion, 1).toString());
    }//GEN-LAST:event_TBAlumnosSinAsigTBPuntajes1MouseClicked

    private void CBCarreraAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCarreraAsigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCarreraAsigActionPerformed

    private void BTN_BuscarEstAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BuscarEstAsigActionPerformed
        // TODO add your handling code here:
        BuscarAlumnosEspecificos();
    }//GEN-LAST:event_BTN_BuscarEstAsigActionPerformed

    private void BTN_BuscarTodosEstAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BuscarTodosEstAsigActionPerformed
        // TODO add your handling code here:
        BuscarTodosAlumnos();
    }//GEN-LAST:event_BTN_BuscarTodosEstAsigActionPerformed

    private void BTN_AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AsignarActionPerformed
        // TODO add your handling code here:
        AsignarAsesor();
    }//GEN-LAST:event_BTN_AsignarActionPerformed

    
    public void BuscarTodosAlumnos() {
        TablaAsigEst = (DefaultTableModel) TBAlumnosSinAsig.getModel();
        int a = TablaAsigEst.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaAsigEst.removeRow(TablaAsigEst.getRowCount() - 1);
        }
        if (mCE.conectar()) {
            ArrayList mArrayListAlumnos = new ArrayList();
            mArrayListAlumnos = mCE.ConsultarTodosAlumnosSinAsig();
            String[] Datos = null;
            if (mArrayListAlumnos != null) {

                for (int i = 0; i < mArrayListAlumnos.size(); i++) {
                    mEstudiante = (Estudiante) mArrayListAlumnos.get(i);
                    Datos = new String[3];
                    //ID_Asesor = mAsesor.getID_Asesor();
                    Datos[0] = String.valueOf(mEstudiante.getId_Estudiante());
                    Datos[1] = mEstudiante.getNombre();
                    Datos[2] = mEstudiante.getCarrera();
                    TablaAsigEst.addRow(Datos);
                }

            } else {
                //LBL_Mensajero2.setText("No hay puntajes");
            }
            this.TBAlumnosSinAsig = new javax.swing.JTable();
            this.TBAlumnosSinAsig.setModel(TablaAsigEst);
            this.TBAlumnosSinAsig.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBAlumnosSinAsig.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBAlumnosSinAsig.getColumnModel().getColumn(1).setPreferredWidth(50);
            if (this.TBAlumnosSinAsig.getRowCount() > 0) {
                this.TBAlumnosSinAsig.setRowSelectionInterval(0, 0);
            }

        } else {
            //LBL_Mensajero2.setText("Error al consultar");
        }

        mCE.desconectar();
    }
    public void LlenarComboCarrera() {
        CBCarreraAsig.addItem("Ninguno");

        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaCarreraEstudiantes();
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBCarreraAsig.addItem(mArrayList.get(i).toString());
                }

            } else {
                JOptionPane.showMessageDialog(null, "No tiene Carreras Dadas de Alta");
            }
            mCE.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "No conectado a la BD");
        }
    }
    public void LlenarComboAsesor() {
        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaAsesorEstudiantes();
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBAsesoresAsignar.addItem(mArrayList.get(i).toString());
                }

            } else {
                JOptionPane.showMessageDialog(null, "No tiene Asesores Dados de Alta");
            }
            mCE.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "No conectado a la BD");
        }
    }
    public void BuscarAlumnosEspecificos() {
        TablaAsigEst = (DefaultTableModel) TBAlumnosSinAsig.getModel();
        int a = TablaAsigEst.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaAsigEst.removeRow(TablaAsigEst.getRowCount() - 1);
        }
        if (mCE.conectar()) {
            ArrayList mArrayListAlumnos = new ArrayList();
            //int IDAsesor = mCE.con(ID_AlumnoParaAsesor);
            mArrayListAlumnos = mCE.ConsultarAlumnosEspecificosSinAsig(CBCarreraAsig.getSelectedItem().toString());
                    //.ConsultarAlumnos(IDAsesor, CBCarreraCons.getSelectedItem().toString(), CBAsesorCons.getSelectedItem().toString());
            String[] Datos = null;
            if (mArrayListAlumnos != null) {

                for (int i = 0; i < mArrayListAlumnos.size(); i++) {
                    mEstudiante = (Estudiante) mArrayListAlumnos.get(i);
                    Datos = new String[3];
                    //ID_Asesor = mAsesor.getID_Asesor();
                    Datos[0] = String.valueOf(mEstudiante.getId_Estudiante());
                    Datos[1] = mEstudiante.getNombre();
                    Datos[2] = mEstudiante.getCarrera();
                    //Datos[2] = 
                    TablaAsigEst.addRow(Datos);
                }

            } else {
                //LBL_Mensajero2.setText("No hay puntajes");
            }
            this.TBAlumnosSinAsig = new javax.swing.JTable();
            this.TBAlumnosSinAsig.setModel(TablaAsigEst);
            this.TBAlumnosSinAsig.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBAlumnosSinAsig.getColumnModel().getColumn(1).setPreferredWidth(50);
            if (this.TBAlumnosSinAsig.getRowCount() > 0) {
                this.TBAlumnosSinAsig.setRowSelectionInterval(0, 0);
            }

        } else {
            //LBL_Mensajero2.setText("Error al consultar");
        }

        mCE.desconectar();
    }
    public void AsignarAsesor() {
            if (mCE.conectar()) {
                ID_AsesorAsignado = mCE.ConsultaIDAsesor(CBAsesoresAsignar.getSelectedItem().toString());
                if (mCE.AsignarAsesorAEstudiante(ID_AlumnoParaAsesor, ID_AsesorAsignado)) {
                    //LBL_Mensajero2.setText("Se realizó un cambio");
                    JOptionPane.showMessageDialog(null, "Cambio realizado");
                    BuscarTodosAlumnos();
                    mCE.desconectar();
                } else {
                    //no se hizo modificacion
                    JOptionPane.showMessageDialog(null, "No se realizó el cambio");
                }
            } else {
                //no conectado
                JOptionPane.showMessageDialog(null, "No conectado a la BD");
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Asignar;
    private javax.swing.JButton BTN_BuscarEstAsig;
    private javax.swing.JButton BTN_BuscarTodosEstAsig;
    private javax.swing.JComboBox<String> CBAsesoresAsignar;
    private javax.swing.JComboBox<String> CBCarreraAsig;
    private javax.swing.JLabel LBL_AlumnoAsig;
    private javax.swing.JTable TBAlumnosSinAsig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
