/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IF_Administrador;

import Clases.*;
import Conexiones.*;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardogarcia
 */
public class IF_GestionAsesores extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_GestionAsesores
     */
    ConexionEduardo mCE = new ConexionEduardo();
    ConexionKevin mCK = new ConexionKevin();
    DefaultTableModel Tabla = new DefaultTableModel();  //para cambios
    DefaultTableModel TablaAlta = new DefaultTableModel();
    DefaultTableModel TablaBaja = new DefaultTableModel();
    DefaultTableModel TablaConsulta = new DefaultTableModel();
    Asesor mAsesor;
    int ID_Asesor = 0, SelecBaja = 0, ID_AsesorBaja = 0;
    String NombreLoginAsesor = "";
    String PassLoginAsesor = "";
    //String SelecBaja = "";
    public IF_GestionAsesores() {
        initComponents();
        LlenarComboPuesto();
        LlenarComboInstitucion();
        LlenarComboPuestoConsulta();
        LlenarComboInstitucionConsulta();
        
        //Para el Alta de Asesor
            TablaAlta.addColumn("ID");
            TablaAlta.addColumn("Nombre");
            TablaAlta.addColumn("Puesto");
            TablaAlta.addColumn("Institucion");
            ConsultaTablaAl();
        
        //Para la baja de Asesor
            TablaBaja.addColumn("ID");
            TablaBaja.addColumn("Nombre");
            TablaBaja.addColumn("Puesto");
            TablaBaja.addColumn("Institucion");
            ConsultaTablaBa();
        
        //Para tabla de Cambios Asesor 
            Tabla.addColumn("ID");
            Tabla.addColumn("Nombre");
            Tabla.addColumn("Puesto");
            Tabla.addColumn("Institucion");
            
        //Para tabla de Consulta Asesor 
            TablaConsulta.addColumn("Nombre");
            TablaConsulta.addColumn("Puesto");
            TablaConsulta.addColumn("Institucion");
            TXTnom3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TXTnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNalta1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_Al = new javax.swing.JTable();
        TXTpuesto = new javax.swing.JTextField();
        TXTemp_inst = new javax.swing.JTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXTnom3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BajAs = new javax.swing.JTable();
        BTNelim = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        CBPuestoR = new javax.swing.JComboBox<>();
        CBInstitucionR = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBAsesores = new javax.swing.JTable();
        TXTNombreNuevo = new javax.swing.JTextField();
        TXTPuestoNuevo = new javax.swing.JTextField();
        TXTInstitucionNueva = new javax.swing.JTextField();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CBPuesto1R = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        CBInstitucion1R = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBAsesores1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setSize(new java.awt.Dimension(650, 620));

        jTabbedPane1.setSize(new java.awt.Dimension(650, 620));

        jLabel1.setText("Nombre: ");

        TXTnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnomActionPerformed(evt);
            }
        });

        jLabel2.setText("Puesto: ");

        jLabel3.setText("Institucion");

        BTNalta1.setText("Guardar");
        BTNalta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNalta1ActionPerformed(evt);
            }
        });

        tbl_Al.setModel(TablaAlta);
        tbl_Al.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_AlTBPuntajes1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_Al);

        TXTpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpuestoActionPerformed(evt);
            }
        });

        TXTemp_inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTemp_instActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTnom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTpuesto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTemp_inst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addComponent(BTNalta1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTemp_inst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BTNalta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Dar de alta un asesor", jPanel1);

        jTabbedPane1.addTab("Alta", jTabbedPane2);

        jLabel4.setText("Nombre: ");

        TXTnom3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnom3KeyTyped(evt);
            }
        });

        tbl_BajAs.setModel(TablaBaja);
        tbl_BajAs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BajAsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_BajAs);

        BTNelim.setText("Eliminar");
        BTNelim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNelimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTnom3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(BTNelim)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTnom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNelim))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Dar de baja un asesor", jPanel2);

        jTabbedPane1.addTab("Baja", jTabbedPane3);

        jLabel11.setText("Puesto:");

        jLabel12.setText("Institución:");

        jLabel16.setText("Nombre:");

        jLabel14.setText("Puesto:");

        jLabel15.setText("Institución:");

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        CBPuestoR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CBPuestoRMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBPuestoRMouseClicked(evt);
            }
        });
        CBPuestoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPuestoRActionPerformed(evt);
            }
        });

        CBInstitucionR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CBInstitucionRMousePressed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        TBAsesores.setModel(Tabla);
        TBAsesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBAsesoresTBPuntajes1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBAsesores);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CBInstitucionR, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBPuestoR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TXTPuestoNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTNombreNuevo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTInstitucionNueva))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPuestoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBInstitucionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTPuestoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTInstitucionNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Cambiar datos de un asesor", jPanel3);

        jTabbedPane1.addTab("Cambios", jTabbedPane4);

        jLabel13.setText("Puesto:");

        CBPuesto1R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPuesto1RActionPerformed(evt);
            }
        });

        jLabel17.setText("Institución:");

        TBAsesores1.setModel(TablaConsulta);
        TBAsesores1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBAsesores1TBPuntajes1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TBAsesores1);

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Ver Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBInstitucion1R, 0, 256, Short.MAX_VALUE)
                            .addComponent(CBPuesto1R, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(CBPuesto1R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBInstitucion1R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Consultar datos de un asesor", jPanel4);

        jTabbedPane1.addTab("Consulta", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ModificarAsesores();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CBPuestoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPuestoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPuestoRActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BuscarAsesoresParaModificar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CBPuestoRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBPuestoRMouseClicked
        // TODO add your handling code here:
        LlenarComboInstitucion();
    }//GEN-LAST:event_CBPuestoRMouseClicked

    private void CBInstitucionRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBInstitucionRMousePressed
        // TODO add your handling code here:
        LlenarComboInstitucion();
    }//GEN-LAST:event_CBInstitucionRMousePressed

    private void CBPuestoRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBPuestoRMousePressed
        // TODO add your handling code here:
        LlenarComboInstitucion();
    }//GEN-LAST:event_CBPuestoRMousePressed

    private void TBAsesoresTBPuntajes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBAsesoresTBPuntajes1MouseClicked
        // TODO add your handling code here:
        //Para llenado
        int Fila = TBAsesores.rowAtPoint(evt.getPoint());
        ID_Asesor = Integer.parseInt(String.valueOf(TBAsesores.getValueAt(Fila, 0)));
        TXTNombreNuevo.setText(String.valueOf(TBAsesores.getValueAt(Fila, 1)));
        TXTPuestoNuevo.setText(String.valueOf(TBAsesores.getValueAt(Fila, 2)));
        TXTInstitucionNueva.setText(String.valueOf(TBAsesores.getValueAt(Fila, 3)));       
    }//GEN-LAST:event_TBAsesoresTBPuntajes1MouseClicked

    private void TXTnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnomActionPerformed

    private void BTNalta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNalta1ActionPerformed
        AgregarAsesor();
    }//GEN-LAST:event_BTNalta1ActionPerformed

    private void tbl_AlTBPuntajes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_AlTBPuntajes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_AlTBPuntajes1MouseClicked

    private void TXTpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTpuestoActionPerformed

    private void TXTemp_instActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTemp_instActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTemp_instActionPerformed

    private void TXTnom3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnom3KeyTyped

    }//GEN-LAST:event_TXTnom3KeyTyped

    private void tbl_BajAsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BajAsMouseClicked
        TXTnom3.setText("");

        SelecBaja = tbl_BajAs.rowAtPoint(evt.getPoint());
        //LBLid.setText(tbl_BajAs.getModel().getValueAt(Selec, 0).toString());
        ID_AsesorBaja = Integer.parseInt(tbl_BajAs.getModel().getValueAt(SelecBaja, 0).toString());
        TXTnom3.setText(tbl_BajAs.getModel().getValueAt(SelecBaja, 1).toString());
    }//GEN-LAST:event_tbl_BajAsMouseClicked

    private void BTNelimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNelimActionPerformed
        EliminarAsesor();
    }//GEN-LAST:event_BTNelimActionPerformed

    private void CBPuesto1RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPuesto1RActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPuesto1RActionPerformed

    private void TBAsesores1TBPuntajes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBAsesores1TBPuntajes1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBAsesores1TBPuntajes1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        BuscarAsesoresEspecificos();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BuscarTodosAsesores();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean ValidarCajaNombreAlta() {
        return !TXTnom.getText().equals("");
    }
    public boolean ValidarCajaPuestoAlta() {
        return !TXTpuesto.getText().equals("");
    }
    public boolean ValidarCajaInstitucionAlta() {
        return !TXTemp_inst.getText().equals("");
    }
    public void ConsultaTablaAl() {
        TablaAlta = (DefaultTableModel) tbl_Al.getModel();
        int a = TablaAlta.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaAlta.removeRow(TablaAlta.getRowCount() - 1);
        }

        if (mCE.conectar()) {
            ArrayList mListaAsesores = mCE.ConsultarTodosAsesores();
            String[] datos;

            for (Object mListaAsesor : mListaAsesores) {
                datos = new String[4];
                mAsesor = (Asesor) mListaAsesor;
                datos[0] = "" + mAsesor.getId_Asesor();
                datos[1] = mAsesor.getNombre();
                datos[2] = mAsesor.getPuesto();
                datos[3] = mAsesor.getEmp_Inst();

                TablaAlta.addRow(datos);
            }
            this.tbl_Al = new javax.swing.JTable();
            this.tbl_Al.setModel(TablaAlta);
            this.tbl_Al.getColumnModel().getColumn(0).setPreferredWidth(250);
            this.tbl_Al.getColumnModel().getColumn(1).setPreferredWidth(250);
            this.tbl_Al.getColumnModel().getColumn(2).setPreferredWidth(250);
            if (this.tbl_Al.getRowCount() > 0) {
                this.tbl_Al.setRowSelectionInterval(0, 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar los asesores");
        }
        mCE.desconectar();
    }
    public void AgregarAsesor() {
        mAsesor = new Asesor();
        String text = TXTnom.getText();
        //text = text.replaceAll(" ", "");
        if (text.length() != 0 && text.length() <= 35) {
            if (ValidarCajaNombreAlta() && ValidarCajaPuestoAlta() && ValidarCajaInstitucionAlta()) {
                if (mCK.conectar()) {
                    mAsesor.setNombre(TXTnom.getText());
                    String separador = Pattern.quote(" ");
                    String[] partes;
                    partes = TXTnom.getText().split(separador);
                    NombreLoginAsesor = partes[0] + "_" + TXTemp_inst.getText();
                    mAsesor.setPuesto(TXTpuesto.getText());
                    mAsesor.setEmp_Inst(TXTemp_inst.getText());
                    if (mCK.AltaAsesor(mAsesor)) {
                        PassLoginAsesor = String.valueOf(mCK.ConsultarIDUltimoAsesor());
                        mCK.AltaAsesorLogin(NombreLoginAsesor, PassLoginAsesor);
                        JOptionPane.showMessageDialog(null, "Asesor agregado exitosamente \n"
                                + "Usuario: " + NombreLoginAsesor + "\n"
                                + "Contraseña: " + PassLoginAsesor + "");
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar Asesor");
                    }
                }
                mCE.desconectar();
            } else {
                JOptionPane.showMessageDialog(null, "Escribe un nombre");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nombre no válido");
        }
        ConsultaTablaAl();
        LlenarComboPuestoConsulta();
        LlenarComboInstitucionConsulta();
        LlenarComboPuesto();
        LlenarComboInstitucion();
        ConsultaTablaBa();
        TXTnom.setText("");
        TXTpuesto.setText("");
        TXTemp_inst.setText("");
        //BuscarAsesoresParaModificar();
    }
    
    public boolean ValidarCajaNombreBaja() {
        return !TXTnom3.getText().equals("");
    }
    public void ConsultaTablaBa() {
        TablaBaja = (DefaultTableModel) tbl_BajAs.getModel();
        int a = TablaBaja.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaBaja.removeRow(TablaBaja.getRowCount() - 1);
        }

        if (mCE.conectar()) {
            ArrayList mListaAsesores = mCE.ConsultarTodosAsesores();
            String[] datos;

            for (Object mListaAsesor : mListaAsesores) {
                datos = new String[4];
                mAsesor = (Asesor) mListaAsesor;
                datos[0] = "" + mAsesor.getId_Asesor();
                datos[1] = mAsesor.getNombre();
                datos[2] = mAsesor.getPuesto();
                datos[3] = mAsesor.getEmp_Inst();

                TablaBaja.addRow(datos);
            }
            this.tbl_BajAs = new javax.swing.JTable();
            this.tbl_BajAs.setModel(TablaBaja);
            this.tbl_BajAs.getColumnModel().getColumn(0).setPreferredWidth(250);
            this.tbl_BajAs.getColumnModel().getColumn(1).setPreferredWidth(250);
            this.tbl_BajAs.getColumnModel().getColumn(2).setPreferredWidth(250);
            if (this.tbl_BajAs.getRowCount() > 0) {
                this.tbl_BajAs.setRowSelectionInterval(0, 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar los asesores");
        }
        mCE.desconectar();
    }
    public void EliminarAsesor() {
        
        String text = TXTnom3.getText();
        text = text.replaceAll(" ", "");
        if (text.length() != 0 && text.length() <= 35) {
            if (mCK.conectar()) {
                if (ValidarCajaNombreBaja()) {
                    mAsesor.setId_Asesor(ID_AsesorBaja);
                    if (mCK.eliminarAsesor(mAsesor)) {
                        JOptionPane.showMessageDialog(null, "Asesor dado de baja exitosamente");
                    } else {
                        JOptionPane.showMessageDialog(null, "Este Asesor tiene relación con otros registros");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecciona el Asesor que deseas eliminar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al conectar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nombre no válido");
        }
        mCE.desconectar();
        ConsultaTablaAl();
        LlenarComboPuestoConsulta();
        LlenarComboInstitucionConsulta();
        LlenarComboPuesto();
        LlenarComboInstitucion();
        ConsultaTablaBa();
        TXTnom3.setText("");
    }

    public void LlenarComboPuesto() {
        CBPuestoR.removeAllItems();
        CBPuestoR.addItem("Ninguno");
        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaPuestoAsesores();
            //LDBLPrueba.setText(mArrayList.get(0).toString());
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBPuestoR.addItem(mArrayList.get(i).toString());

                }

            } else {
                //LBL_Mensajero2.setText("No tiene Equipos Dados de Alta");
            }
            mCE.desconectar();
        } else {
            //LBL_Mensajero2.setText("No conectado a la BD");
        }
    }
    public void LlenarComboInstitucion() {
        CBInstitucionR.removeAllItems();
        CBInstitucionR.addItem("Ninguno");
        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaInstitucionAsesores();
            //LDBLPrueba.setText(mArrayList.get(0).toString());
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBInstitucionR.addItem(mArrayList.get(i).toString());
                }

            } else {
                //LBL_Mensajero2.setText("No tiene Equipos Dados de Alta");
            }
            mCE.desconectar();
        } else {
            //LBL_Mensajero2.setText("No conectado a la BD");
        }
    }
    public void LimpiarTabla() {
        Tabla = (DefaultTableModel) TBAsesores.getModel();
        int a = TBAsesores.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            Tabla.removeRow(Tabla.getRowCount() - 1);
        }
    }  
    public void BuscarAsesoresParaModificar() {
        LimpiarTabla();
        if (mCE.conectar()) {
            ArrayList mArrayListAsesores = new ArrayList();
            mArrayListAsesores = mCE.ConsultarAsesores(CBPuestoR.getSelectedItem().toString(), CBInstitucionR.getSelectedItem().toString());
            String[] Datos = null;
            
            if (mArrayListAsesores != null) {

                for (int i = 0; i < mArrayListAsesores.size(); i++) {
                    mAsesor = (Asesor) mArrayListAsesores.get(i);
                    Datos = new String[4];
                    ID_Asesor = mAsesor.getId_Asesor();
                    Datos[0] = String.valueOf(mAsesor.getId_Asesor());
                    Datos[1] = mAsesor.getNombre();
                    Datos[2] = mAsesor.getPuesto();
                    Datos[3] = mAsesor.getEmp_Inst();
                    Tabla.addRow(Datos);
                }

            } else {
                //LBL_Mensajero2.setText("No hay puntajes");
            }
            this.TBAsesores = new javax.swing.JTable();
            this.TBAsesores.setModel(Tabla);
            this.TBAsesores.getColumnModel().getColumn(0).setPreferredWidth(5);
            this.TBAsesores.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBAsesores.getColumnModel().getColumn(2).setPreferredWidth(50);
            this.TBAsesores.getColumnModel().getColumn(3).setPreferredWidth(100);
            if (this.TBAsesores.getRowCount() > 0) {
                this.TBAsesores.setRowSelectionInterval(0, 0);
            }

        } else {
            //LBL_Mensajero2.setText("Error al consultar");
        }

        mCE.desconectar();
    }
    public boolean ValidarCajaNombre() {
        return !TXTNombreNuevo.getText().equals("");
    }
    public boolean ValidarCajaPuesto() {
        return !TXTPuestoNuevo.getText().equals("");
    }
    public boolean ValidarCajaInstitucion() {
        return !TXTInstitucionNueva.getText().equals("");
    }
    public void ModificarAsesores() {
        if (ValidarCajaNombre() && ValidarCajaPuesto() && ValidarCajaInstitucion()) {
            if (mCE.conectar()) {
                if (mCE.ModificarAsesores(ID_Asesor, TXTNombreNuevo.getText(), TXTPuestoNuevo.getText(), TXTInstitucionNueva.getText())) {
                    //LBL_Mensajero2.setText("Se realizó un cambio");
                    JOptionPane.showMessageDialog(null, "Cambio realizado");
                    BuscarAsesoresParaModificar();
                    mCE.desconectar();
                } else {
                    //no se hizo modificacion
                    JOptionPane.showMessageDialog(null, "No se realizó el cambio");
                }
            } else {
                //no conectado
                JOptionPane.showMessageDialog(null, "No conectado a la BD");
            }
        } else {
            //llenar bien campos
            JOptionPane.showMessageDialog(null, "Llenar bien los campos");
        }
        ConsultaTablaAl();
        LlenarComboPuestoConsulta();
        LlenarComboInstitucionConsulta();
        LlenarComboPuesto();
        LlenarComboInstitucion();
        ConsultaTablaBa();
        TXTNombreNuevo.setText("");
        TXTPuestoNuevo.setText("");
        TXTInstitucionNueva.setText("");
    }
    
    public void LlenarComboPuestoConsulta() {
        CBPuesto1R.removeAllItems();
        CBPuesto1R.addItem("Ninguno");
        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaPuestoAsesores();
            //LDBLPrueba.setText(mArrayList.get(0).toString());
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBPuesto1R.addItem(mArrayList.get(i).toString());

                }

            } else {
                //LBL_Mensajero2.setText("No tiene Equipos Dados de Alta");
            }
            mCE.desconectar();
        } else {
            //LBL_Mensajero2.setText("No conectado a la BD");
        }
    }
    public void LlenarComboInstitucionConsulta() {
        CBInstitucion1R.removeAllItems();
        CBInstitucion1R.addItem("Ninguno");
        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaInstitucionAsesores();
            //LDBLPrueba.setText(mArrayList.get(0).toString());
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CBInstitucion1R.addItem(mArrayList.get(i).toString());
                }

            } else {
                //LBL_Mensajero2.setText("No tiene Equipos Dados de Alta");
            }
            mCE.desconectar();
        } else {
            //LBL_Mensajero2.setText("No conectado a la BD");
        }
    }
    public void BuscarAsesoresEspecificos() {
        TablaConsulta = (DefaultTableModel) TBAsesores1.getModel();
        int a = TablaConsulta.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaConsulta.removeRow(TablaConsulta.getRowCount() - 1);
        }
        if (mCE.conectar()) {
            ArrayList mArrayListAsesores = new ArrayList();
            mArrayListAsesores = mCE.ConsultarAsesores(CBPuesto1R.getSelectedItem().toString(), CBInstitucion1R.getSelectedItem().toString());
            String[] Datos = null;
            if (mArrayListAsesores != null) {

                for (int i = 0; i < mArrayListAsesores.size(); i++) {
                    mAsesor = (Asesor) mArrayListAsesores.get(i);
                    Datos = new String[3];
                    //ID_Asesor = mAsesor.getId_Asesor();
                    Datos[0] = mAsesor.getNombre();
                    Datos[1] = mAsesor.getPuesto();
                    Datos[2] = mAsesor.getEmp_Inst();
                    TablaConsulta.addRow(Datos);
                }

            } else {
                //LBL_Mensajero2.setText("No hay puntajes");
            }
            this.TBAsesores1 = new javax.swing.JTable();
            this.TBAsesores1.setModel(TablaConsulta);
            this.TBAsesores1.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBAsesores1.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBAsesores1.getColumnModel().getColumn(2).setPreferredWidth(100);
            if (this.TBAsesores1.getRowCount() > 0) {
                this.TBAsesores1.setRowSelectionInterval(0, 0);
            }

        } else {
            //LBL_Mensajero2.setText("Error al consultar");
        }

        mCE.desconectar();
    }
    public void BuscarTodosAsesores() {
        TablaConsulta = (DefaultTableModel) TBAsesores1.getModel();
        int a = TablaConsulta.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            TablaConsulta.removeRow(TablaConsulta.getRowCount() - 1);
        }
        if (mCE.conectar()) {
            ArrayList mArrayListAsesores = new ArrayList();
            mArrayListAsesores = mCE.ConsultarTodosAsesores();
            String[] Datos = null;
            if (mArrayListAsesores != null) {

                for (int i = 0; i < mArrayListAsesores.size(); i++) {
                    mAsesor = (Asesor) mArrayListAsesores.get(i);
                    Datos = new String[3];
                    ID_Asesor = mAsesor.getId_Asesor();
                    Datos[0] = mAsesor.getNombre();
                    Datos[1] = mAsesor.getPuesto();
                    Datos[2] = mAsesor.getEmp_Inst();
                    TablaConsulta.addRow(Datos);
                }

            } else {
                //LBL_Mensajero2.setText("No hay puntajes");
            }
            this.TBAsesores1 = new javax.swing.JTable();
            this.TBAsesores1.setModel(TablaConsulta);
            this.TBAsesores1.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBAsesores1.getColumnModel().getColumn(1).setPreferredWidth(50);
            this.TBAsesores1.getColumnModel().getColumn(2).setPreferredWidth(100);
            if (this.TBAsesores1.getRowCount() > 0) {
                this.TBAsesores1.setRowSelectionInterval(0, 0);
            }

        } else {
            //LBL_Mensajero2.setText("Error al consultar");
        }

        mCE.desconectar();
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNalta1;
    private javax.swing.JButton BTNelim;
    private javax.swing.JComboBox<String> CBInstitucion1R;
    private javax.swing.JComboBox<String> CBInstitucionR;
    private javax.swing.JComboBox<String> CBPuesto1R;
    private javax.swing.JComboBox<String> CBPuestoR;
    private javax.swing.JTable TBAsesores;
    private javax.swing.JTable TBAsesores1;
    private javax.swing.JTextField TXTInstitucionNueva;
    private javax.swing.JTextField TXTNombreNuevo;
    private javax.swing.JTextField TXTPuestoNuevo;
    private javax.swing.JTextField TXTemp_inst;
    private javax.swing.JTextField TXTnom;
    private javax.swing.JTextField TXTnom3;
    private javax.swing.JTextField TXTpuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tbl_Al;
    private javax.swing.JTable tbl_BajAs;
    // End of variables declaration//GEN-END:variables
}
