/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IF_Estudiante;

import Clases.PDF.*;
import Conexiones.*;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author eduardogarcia
 */
public class IF_SubirDocumentoEstudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form IF_SubirDocumentoEstudiante
     */
    
    ConexionEduardo mCE = new ConexionEduardo();
    Tabla_PdfVO tpdf = new Tabla_PdfVO();
    String ruta_archivo = "";
    int id = -1;
    String Titulo = "";
    String Tipo = "";
    int idDocumento = 0;
    String Status = "";
    public int idExpediente = 0;
    public int idEstudiante = 0;
    public int idUltimoDoc = 0;
    
    public IF_SubirDocumentoEstudiante() {
        initComponents();
        LlenarComboCarrera();
        LlenarComboEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TXTRuta = new javax.swing.JTextField();
        TXTTitulo = new javax.swing.JTextField();
        TXTTipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_SubirDoc = new javax.swing.JButton();
        CB_Expedientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CB_Estudiantes = new javax.swing.JComboBox<>();

        setBorder(null);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TXTRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTRutaActionPerformed(evt);
            }
        });

        TXTTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTituloActionPerformed(evt);
            }
        });

        jLabel1.setText("Título");

        jLabel2.setText("Tipo");

        BTN_SubirDoc.setText("Subir");
        BTN_SubirDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SubirDocActionPerformed(evt);
            }
        });

        jLabel3.setText("Expediente");

        jLabel4.setText("Estudiante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTTitulo)
                            .addComponent(TXTTipo)
                            .addComponent(CB_Expedientes, 0, 338, Short.MAX_VALUE)
                            .addComponent(CB_Estudiantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTRuta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(BTN_SubirDoc)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CB_Expedientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CB_Estudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(TXTRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(BTN_SubirDoc)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRutaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de archivos pdf(*.pdf)", "pdf");
        
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        int ventana = archivo.showOpenDialog(null);
        
        if(ventana == JFileChooser.APPROVE_OPTION) {
            File file = archivo.getSelectedFile();
            TXTRuta.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(TXTRuta.getText());
            foto = foto.getScaledInstance(300, 400, Image.SCALE_DEFAULT);
            //jLabel1.setIcon(new ImageIcon(foto));
        } else {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTN_SubirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SubirDocActionPerformed
        // TODO add your handling code here:
        String Titulo = TXTTitulo.getText();
        String Tipo = TXTTipo.getText();
        
        String Ruta = TXTRuta.getText();
        sql s = new sql();
        int codigo = s.auto_increment("SELECT MAX(idDocumento) FROM Documento;");
        File ruta = new File(TXTRuta.getText());
        if (Titulo.trim().length() != 0 && TXTRuta.getText().trim().length() != 0 && !"Ninguno".equals(CB_Expedientes.getSelectedItem().toString()) && !"Ninguno".equals(CB_Estudiantes.getSelectedItem().toString())) {

            guardar_pdf(idDocumento, Titulo, Tipo, ruta);
            if (mCE.conectar()) {
                idExpediente = mCE.ConsultarIDExpediente(CB_Expedientes.getSelectedItem().toString());
                idEstudiante = mCE.ConsultarIDAlumnos(CB_Estudiantes.getSelectedItem().toString());
                idUltimoDoc = mCE.ConsultarIDUltimoDoc();
                Status = "No revisado";
                mCE.ModificarDocumentos(idUltimoDoc, idExpediente, idEstudiante, Status);
                mCE.desconectar();
            } else {
                JOptionPane.showMessageDialog(null, "Conectar con la Base de Datos");
            }
            //tpdf.visualizar_PdfVO(tabla);
            TXTRuta.setText("");
            //activa_boton(false, false, false);
            TXTTitulo.setText("");
            TXTTipo.setText("");
            CB_Estudiantes.setSelectedItem("Ninguno");
            CB_Expedientes.setSelectedItem("Ninguno");
            JOptionPane.showMessageDialog(null, "Archivo subido con exito");
        } else {
            JOptionPane.showMessageDialog(null, "Rellenar todo los campos");
        }
    }//GEN-LAST:event_BTN_SubirDocActionPerformed

    private void TXTTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTituloActionPerformed

    public void guardar_pdf(int idDoc, String titulo, String tipo, File ruta) {
        PdfDAO pa = new PdfDAO();
        PdfVO po = new PdfVO();
        po.setId(idDoc);
        po.setTitulopdf(titulo);
        po.setTipopdf(tipo);      
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setArchivopdf(pdf);
        } catch (IOException ex) {
            po.setArchivopdf(null);
            JOptionPane.showMessageDialog(null, "Error al agregar archivo pdf "+ex.getMessage());
        }
        //po.setExpediente(Expediente);
        //po.setEstudiante(Estudiante);
        pa.Agregar_PdfVO(po);
    }
    
    public void LlenarComboCarrera() {
        CB_Expedientes.addItem("Ninguno");

        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultaNombreExpedientes();
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CB_Expedientes.addItem(mArrayList.get(i).toString());
                }

            } else {
                JOptionPane.showMessageDialog(null, "No tiene expedientes Dados de Alta");
            }
            mCE.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "No conectado a la BD");
        }
    }
    public void LlenarComboEstudiantes() {
        CB_Estudiantes.addItem("Ninguno");

        if (mCE.conectar()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mCE.ConsultarAlumnosEspecificosConAsig();
            if (mArrayList != null) {

                for (int i = 0; i < mArrayList.size(); i++) {
                    CB_Estudiantes.addItem(mArrayList.get(i).toString());
                }

            } else {
                JOptionPane.showMessageDialog(null, "No tiene expedientes Dados de Alta");
            }
            mCE.desconectar();
        } else {
            JOptionPane.showMessageDialog(null, "No conectado a la BD");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_SubirDoc;
    private javax.swing.JComboBox<String> CB_Estudiantes;
    private javax.swing.JComboBox<String> CB_Expedientes;
    private javax.swing.JTextField TXTRuta;
    private javax.swing.JTextField TXTTipo;
    private javax.swing.JTextField TXTTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
